"use client";

import React, { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Copy,
  Check,
  Download,
  Sparkles,
  Lightbulb,
  RotateCcw,
  ChevronDown,
  ChevronUp,
  FileText,
  Clock,
  Layers,
} from "lucide-react";
import type { ProcessResult } from "@/types";

interface ResultsViewProps {
  result: ProcessResult;
  onReset: () => void;
}

function useCopyToClipboard(timeout = 2000) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(
    async (text: string) => {
      try {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), timeout);
      } catch {
        const el = document.createElement("textarea");
        el.value = text;
        el.style.position = "fixed";
        el.style.opacity = "0";
        document.body.appendChild(el);
        el.select();
        document.execCommand("copy");
        document.body.removeChild(el);
        setCopied(true);
        setTimeout(() => setCopied(false), timeout);
      }
    },
    [timeout]
  );
  return { copied, copy };
}

function buildDownloadText(result: ProcessResult): string {
  const lines: string[] = [
    "DOCUMENT SUMMARY",
    "================",
    "",
    `Source: ${result.meta.sourceType === "pdf" ? "PDF document" : "Image / Scanned document"}`,
    `Pages: ${result.meta.pages}`,
    `Processing time: ${(result.meta.processingTimeMs / 1000).toFixed(1)}s`,
    "",
    "SUMMARY",
    "-------",
    result.summary,
    "",
    "KEY POINTS",
    "----------",
    ...result.keyPoints.map((p, i) => `${i + 1}. ${p}`),
  ];

  if (result.improvementSuggestions?.length) {
    lines.push(
      "",
      "IMPROVEMENT SUGGESTIONS",
      "-----------------------",
      ...result.improvementSuggestions.map((s, i) => `${i + 1}. ${s}`)
    );
  }

  lines.push(
    "",
    "---",
    `Generated by Document Summary Assistant · ${new Date().toLocaleDateString()}`
  );

  return lines.join("\n");
}

export function ResultsView({ result, onReset }: ResultsViewProps) {
  const { copied: summaryCopied, copy: copySummary } = useCopyToClipboard();
  const [showTextPreview, setShowTextPreview] = useState(false);

  const fullCopyText = buildDownloadText(result);

  const handleDownload = () => {
    const blob = new Blob([fullCopyText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "summary.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const cardBase =
    "relative rounded-2xl overflow-hidden border border-white/[0.08] bg-white/[0.03] backdrop-blur-xl";

  return (
    <motion.div
      className="w-full flex flex-col gap-5"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
    >
      {/* ── Header row ──────────────────────────────────────────────────── */}
      <motion.div
        className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"
        initial={{ opacity: 0, y: -12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
      >
        <div>
          <h2 className="text-white text-2xl font-semibold tracking-tight">
            Summary ready
          </h2>
          <div className="flex items-center gap-3 mt-1.5 flex-wrap">
            <span className="flex items-center gap-1.5 text-xs text-white/35">
              <FileText className="w-3.5 h-3.5" aria-hidden />
              {result.meta.sourceType === "pdf" ? "PDF" : "Image"}
            </span>
            <span className="w-1 h-1 rounded-full bg-white/20" />
            <span className="flex items-center gap-1.5 text-xs text-white/35">
              <Layers className="w-3.5 h-3.5" aria-hidden />
              {result.meta.pages} page{result.meta.pages !== 1 ? "s" : ""}
            </span>
            <span className="w-1 h-1 rounded-full bg-white/20" />
            <span className="flex items-center gap-1.5 text-xs text-white/35">
              <Clock className="w-3.5 h-3.5" aria-hidden />
              {(result.meta.processingTimeMs / 1000).toFixed(1)}s
            </span>
          </div>
        </div>

        <button
          onClick={onReset}
          className="flex items-center gap-2 text-sm text-white/50 hover:text-white/90 transition-colors border border-white/10 hover:border-white/25 rounded-full px-4 py-2 backdrop-blur-sm bg-white/[0.03] self-start sm:self-auto"
        >
          <RotateCcw className="w-3.5 h-3.5" aria-hidden />
          New document
        </button>
      </motion.div>

      {/* ── Summary Card ────────────────────────────────────────────────── */}
      <motion.div
        className={cardBase}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.15, ease: [0.16, 1, 0.3, 1] }}
      >
        {/* Accent glow */}
        <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/20 to-transparent" />

        <div className="p-7">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-6 h-6 rounded-lg bg-white/8 flex items-center justify-center">
              <FileText className="w-3.5 h-3.5 text-white/60" aria-hidden />
            </div>
            <span className="text-xs font-semibold tracking-widest uppercase text-white/40">
              Summary
            </span>
          </div>
          <p className="text-white/80 leading-[1.8] text-base">{result.summary}</p>
        </div>
      </motion.div>

      {/* ── Key Points Card ─────────────────────────────────────────────── */}
      <motion.div
        className={cardBase}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.25, ease: [0.16, 1, 0.3, 1] }}
      >
        <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/15 to-transparent" />

        <div className="p-7">
          <div className="flex items-center gap-2 mb-5">
            <div className="w-6 h-6 rounded-lg bg-white/8 flex items-center justify-center">
              <Sparkles className="w-3.5 h-3.5 text-white/60" aria-hidden />
            </div>
            <span className="text-xs font-semibold tracking-widest uppercase text-white/40">
              Key Points
            </span>
          </div>

          <ul className="space-y-4">
            {result.keyPoints.map((point, i) => (
              <motion.li
                key={i}
                className="flex items-start gap-4"
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 + i * 0.07, duration: 0.45 }}
              >
                <span className="flex-shrink-0 w-5 h-5 rounded-full bg-white/8 border border-white/10 flex items-center justify-center mt-0.5">
                  <span className="text-[10px] font-mono text-white/40 leading-none">
                    {i + 1}
                  </span>
                </span>
                <span className="text-white/70 text-sm leading-[1.75]">{point}</span>
              </motion.li>
            ))}
          </ul>
        </div>
      </motion.div>

      {/* ── Improvement Suggestions Card ────────────────────────────────── */}
      {result.improvementSuggestions?.length > 0 && (
        <motion.div
          className={cardBase}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.35, ease: [0.16, 1, 0.3, 1] }}
        >
          <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
          {/* Amber tinted inner glow */}
          <div className="absolute inset-0 bg-gradient-to-br from-amber-500/[0.03] via-transparent to-transparent pointer-events-none" />

          <div className="relative p-7">
            <div className="flex items-center gap-2 mb-5">
              <div className="w-6 h-6 rounded-lg bg-amber-500/10 flex items-center justify-center">
                <Lightbulb className="w-3.5 h-3.5 text-amber-400/70" aria-hidden />
              </div>
              <span className="text-xs font-semibold tracking-widest uppercase text-white/35">
                Improvement Suggestions
              </span>
            </div>

            <ul className="space-y-4">
              {result.improvementSuggestions.map((suggestion, i) => (
                <motion.li
                  key={i}
                  className="flex items-start gap-4"
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.4 + i * 0.07, duration: 0.45 }}
                >
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-amber-500/10 border border-amber-500/15 flex items-center justify-center mt-0.5">
                    <span className="text-[10px] font-mono text-amber-400/50 leading-none">
                      {i + 1}
                    </span>
                  </span>
                  <span className="text-white/55 text-sm leading-[1.75]">{suggestion}</span>
                </motion.li>
              ))}
            </ul>
          </div>
        </motion.div>
      )}

      {/* ── Action buttons ───────────────────────────────────────────────── */}
      <motion.div
        className="flex flex-wrap items-center gap-3 pt-1"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
      >
        <button
          onClick={() => copySummary(fullCopyText)}
          className="flex items-center gap-2 text-sm text-white/70 hover:text-white border border-white/10 hover:border-white/25 rounded-full px-5 py-2.5 backdrop-blur-sm bg-white/[0.03] hover:bg-white/[0.06] transition-all"
          aria-label="Copy summary to clipboard"
        >
          <AnimatePresence mode="wait" initial={false}>
            {summaryCopied ? (
              <motion.span
                key="check"
                className="flex items-center gap-2"
                initial={{ opacity: 0, scale: 0.85 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.85 }}
              >
                <Check className="w-3.5 h-3.5 text-emerald-400" aria-hidden />
                Copied!
              </motion.span>
            ) : (
              <motion.span
                key="copy"
                className="flex items-center gap-2"
                initial={{ opacity: 0, scale: 0.85 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.85 }}
              >
                <Copy className="w-3.5 h-3.5" aria-hidden />
                Copy all
              </motion.span>
            )}
          </AnimatePresence>
        </button>

        <button
          onClick={handleDownload}
          className="flex items-center gap-2 text-sm text-white/70 hover:text-white border border-white/10 hover:border-white/25 rounded-full px-5 py-2.5 backdrop-blur-sm bg-white/[0.03] hover:bg-white/[0.06] transition-all"
          aria-label="Download summary as text file"
        >
          <Download className="w-3.5 h-3.5" aria-hidden />
          Download .txt
        </button>
      </motion.div>

      {/* ── Extracted text preview (collapsible) ─────────────────────────── */}
      {result.extractedTextPreview && (
        <motion.div
          className="mt-1"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
        >
          <button
            onClick={() => setShowTextPreview((v) => !v)}
            className="flex items-center gap-1.5 text-xs text-white/25 hover:text-white/45 transition-colors cursor-pointer mb-3"
            aria-expanded={showTextPreview}
          >
            {showTextPreview ? (
              <ChevronUp className="w-3.5 h-3.5" aria-hidden />
            ) : (
              <ChevronDown className="w-3.5 h-3.5" aria-hidden />
            )}
            {showTextPreview ? "Hide" : "Show"} extracted text preview
          </button>

          <AnimatePresence>
            {showTextPreview && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.3 }}
                className="overflow-hidden"
              >
                <div className={`${cardBase} p-5`}>
                  <p className="text-xs text-white/25 tracking-widest uppercase mb-3 font-semibold">
                    Extracted Text Preview
                  </p>
                  <p className="text-white/35 text-xs leading-relaxed font-mono whitespace-pre-wrap break-words">
                    {result.extractedTextPreview}
                  </p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      )}
    </motion.div>
  );
}
