"use client";

import React, { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Copy, Check, Download } from "lucide-react";
import type { ProcessResult } from "@/types";

interface SummaryActionsProps {
  result: ProcessResult;
  documentName: string;
}

function useCopyToClipboard(timeout = 2000) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(
    async (text: string) => {
      try {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), timeout);
      } catch {
        // Fallback
        const el = document.createElement("textarea");
        el.value = text;
        el.style.cssText = "position:fixed;opacity:0;pointer-events:none";
        document.body.appendChild(el);
        el.select();
        document.execCommand("copy");
        document.body.removeChild(el);
        setCopied(true);
        setTimeout(() => setCopied(false), timeout);
      }
    },
    [timeout]
  );
  return { copied, copy };
}

function buildDownloadText(result: ProcessResult, documentName: string): string {
  const lines: string[] = [
    "DOCUMENT SUMMARY",
    "================",
    "",
    `Source: ${documentName}`,
    `Type: ${result.meta.sourceType === "pdf" ? "PDF document" : "Image / Scanned document"}`,
    `Pages: ${result.meta.pages}`,
    `Processing time: ${(result.meta.processingTimeMs / 1000).toFixed(1)}s`,
    "",
    "SUMMARY",
    "-------",
    result.summary,
    "",
    "KEY POINTS",
    "----------",
    ...result.keyPoints.map((p, i) => `${i + 1}. ${p}`),
  ];

  if (result.improvementSuggestions?.length) {
    lines.push(
      "",
      "IMPROVEMENT SUGGESTIONS",
      "-----------------------",
      ...result.improvementSuggestions.map((s, i) => `${i + 1}. ${s}`)
    );
  }

  lines.push(
    "",
    "---",
    `Generated by DocSummary · ${new Date().toLocaleDateString()}`
  );

  return lines.join("\n");
}

export function SummaryActions({ result, documentName }: SummaryActionsProps) {
  const { copied, copy } = useCopyToClipboard();

  const fullText = buildDownloadText(result, documentName);

  const handleDownload = () => {
    const blob = new Blob([fullText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const baseName = documentName.replace(/\.[^.]+$/, "") || "summary";
    a.download = `${baseName}-summary.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      className="flex flex-wrap items-center gap-3"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ delay: 0.55 }}
    >
      <button
        onClick={() => copy(result.summary)}
        className="flex items-center gap-2 text-sm text-white/70 hover:text-white border border-white/10 hover:border-white/25 rounded-full px-5 py-2.5 backdrop-blur-sm bg-white/[0.03] hover:bg-white/[0.06] transition-all"
        aria-label="Copy summary to clipboard"
      >
        <AnimatePresence mode="wait" initial={false}>
          {copied ? (
            <motion.span
              key="check"
              className="flex items-center gap-2"
              initial={{ opacity: 0, scale: 0.85 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.85 }}
            >
              <Check className="w-3.5 h-3.5 text-emerald-400" aria-hidden />
              Copied!
            </motion.span>
          ) : (
            <motion.span
              key="copy"
              className="flex items-center gap-2"
              initial={{ opacity: 0, scale: 0.85 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.85 }}
            >
              <Copy className="w-3.5 h-3.5" aria-hidden />
              Copy Summary
            </motion.span>
          )}
        </AnimatePresence>
      </button>

      <button
        onClick={handleDownload}
        className="flex items-center gap-2 text-sm text-white/70 hover:text-white border border-white/10 hover:border-white/25 rounded-full px-5 py-2.5 backdrop-blur-sm bg-white/[0.03] hover:bg-white/[0.06] transition-all"
        aria-label="Download summary as text file"
      >
        <Download className="w-3.5 h-3.5" aria-hidden />
        Download .txt
      </button>
    </motion.div>
  );
}
