"use client";

import React, { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Copy, Check, Download } from "lucide-react";
import type { ProcessResult } from "@/types";

interface SummaryActionsProps {
  result: ProcessResult;
  documentName: string;
}

function useCopyToClipboard(timeout = 2000) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(
    async (text: string) => {
      try {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), timeout);
      } catch {
        const el = document.createElement("textarea");
        el.value = text;
        el.style.cssText = "position:fixed;opacity:0;pointer-events:none";
        document.body.appendChild(el);
        el.select();
        document.execCommand("copy");
        document.body.removeChild(el);
        setCopied(true);
        setTimeout(() => setCopied(false), timeout);
      }
    },
    [timeout]
  );
  return { copied, copy };
}

function buildDownloadText(result: ProcessResult, documentName: string): string {
  const lines: string[] = [
    "DOCUMENT SUMMARY",
    "================",
    "",
    `Source: ${documentName}`,
    `Type: ${result.meta.sourceType === "pdf" ? "PDF document" : "Image / Scanned document"}`,
    `Pages: ${result.meta.pages}`,
    `Processing time: ${(result.meta.processingTimeMs / 1000).toFixed(1)}s`,
    "",
    "SUMMARY",
    "-------",
    result.summary,
    "",
    "KEY POINTS",
    "----------",
    ...result.keyPoints.map((p, i) => `${i + 1}. ${p}`),
  ];

  if (result.improvementSuggestions?.length) {
    lines.push(
      "",
      "IMPROVEMENT SUGGESTIONS",
      "-----------------------",
      ...result.improvementSuggestions.map((s, i) => `${i + 1}. ${s}`)
    );
  }

  lines.push(
    "",
    "---",
    `Generated by DocSummary · ${new Date().toLocaleDateString()}`
  );

  return lines.join("\n");
}

const btnBase: React.CSSProperties = {
  fontFamily: "'Patrick Hand', cursive",
  fontSize: "0.95rem",
  color: "#2d2d2d",
  background: "#ffffff",
  border: "2px solid #2d2d2d",
  borderRadius: "255px 15px 225px 15px / 15px 225px 15px 255px",
  boxShadow: "4px 4px 0px 0px #2d2d2d",
  padding: "0.55rem 1.3rem",
  display: "flex",
  alignItems: "center",
  gap: "0.5rem",
  cursor: "pointer",
  transition: "all 0.1s ease",
};

export function SummaryActions({ result, documentName }: SummaryActionsProps) {
  const { copied, copy } = useCopyToClipboard();

  const fullText = buildDownloadText(result, documentName);

  const handleDownload = () => {
    const blob = new Blob([fullText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const baseName = documentName.replace(/\.[^.]+$/, "") || "summary";
    a.download = `${baseName}-summary.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleHover = (el: HTMLElement, hovered: boolean) => {
    el.style.background = hovered ? "#2d5da1" : "#ffffff";
    el.style.color = hovered ? "#ffffff" : "#2d2d2d";
    el.style.boxShadow = hovered ? "2px 2px 0px 0px #2d2d2d" : "4px 4px 0px 0px #2d2d2d";
    el.style.transform = hovered ? "translate(2px, 2px)" : "translate(0, 0)";
  };

  return (
    <motion.div
      className="flex flex-wrap items-center gap-3"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ delay: 0.55 }}
    >
      {/* Copy Summary */}
      <button
        onClick={() => copy(result.summary)}
        style={btnBase}
        aria-label="Copy summary to clipboard"
        onMouseEnter={(e) => handleHover(e.currentTarget, true)}
        onMouseLeave={(e) => handleHover(e.currentTarget, false)}
        onMouseDown={(e) => {
          (e.currentTarget as HTMLElement).style.boxShadow = "0px 0px 0px 0px #2d2d2d";
          (e.currentTarget as HTMLElement).style.transform = "translate(4px, 4px)";
        }}
        onMouseUp={(e) => handleHover(e.currentTarget, true)}
      >
        <AnimatePresence mode="wait" initial={false}>
          {copied ? (
            <motion.span
              key="check"
              className="flex items-center gap-2"
              initial={{ opacity: 0, scale: 0.85 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.85 }}
            >
              <Check className="w-4 h-4" strokeWidth={2.5} style={{ color: "#2d2d2d" }} aria-hidden />
              Copied!
            </motion.span>
          ) : (
            <motion.span
              key="copy"
              className="flex items-center gap-2"
              initial={{ opacity: 0, scale: 0.85 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.85 }}
            >
              <Copy className="w-4 h-4" strokeWidth={2.5} aria-hidden />
              Copy Summary
            </motion.span>
          )}
        </AnimatePresence>
      </button>

      {/* Download */}
      <button
        onClick={handleDownload}
        style={{
          ...btnBase,
          borderRadius: "15px 255px 15px 225px / 225px 15px 255px 15px",
        }}
        aria-label="Download summary as text file"
        onMouseEnter={(e) => handleHover(e.currentTarget, true)}
        onMouseLeave={(e) => handleHover(e.currentTarget, false)}
        onMouseDown={(e) => {
          (e.currentTarget as HTMLElement).style.boxShadow = "0px 0px 0px 0px #2d2d2d";
          (e.currentTarget as HTMLElement).style.transform = "translate(4px, 4px)";
        }}
        onMouseUp={(e) => handleHover(e.currentTarget, true)}
      >
        <Download className="w-4 h-4" strokeWidth={2.5} aria-hidden />
        Download .txt
      </button>
    </motion.div>
  );
}
